### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by guahunyo** [chaojie/ComfyUI-AniPortrait#4]
![image](https://github.com/chaojie/ComfyUI-AniPortrait/assets/18573180/71fc2dbb-104d-46e0-a370-0af340c6ab92)
![image](https://github.com/chaojie/ComfyUI-AniPortrait/assets/18573180/25ddb7c0-5979-4d52-9fb0-fc2fdd27ce7a)
![image](https://github.com/chaojie/ComfyUI-AniPortrait/assets/18573180/edea5a40-9d99-4e27-b60d-bc7d7226a310)

Failed to validate prompt for output 7:
* (prompt):
  - Return type mismatch between linked nodes: frame_rate, FLOAT != INT
* LoadImage 4:
  - Custom validation failed for node: image - Invalid image file: 1.png
* VHS_VideoCombine 7:
  - Return type mismatch between linked nodes: frame_rate, FLOAT != INT
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': 'Return type mismatch between linked nodes: frame_rate, FLOAT != INT', 'extra_info': {}}
win11 路径都改了 运行报错

**Comment by chaojie** [comment]
删掉loadimage跟VHS_VideoCombine两个节点，你自己添加这两个节点试试。可能版本不同，我的VHS_VideoCombine里frame_rate是float，你重新添加后就手动输入30就好了，不需要连接

**Comment by chaojie** [comment]
路径不用改代码啊。你就在节点上输入路径就行了。windows上最好也写D:/这样好一些，把\都改成/试一下

**Comment by guahunyo** [comment]
> 路径不用改代码啊。你就在节点上输入路径就行了。windows上最好也写D:/这样好一些，把\都改成/试一下

好的谢谢 我试试

**Comment by guahunyo** [comment]
> 路径不用改代码啊。你就在节点上输入路径就行了。windows上最好也写D:/这样好一些，把\都改成/试一下

![image](https://github.com/chaojie/ComfyUI-AniPortrait/assets/18573180/c01f8f40-4215-4128-bca6-495551c922e0)


![image](https://github.com/chaojie/ComfyUI-AniPortrait/assets/18573180/273f4ddb-5bc6-4860-9f5c-1fadb4b56414)
为了排除错误 我把其他所有节点都拿走了 只留下四个节点  然后卡在这里了

**Comment by guahunyo** [comment]
usage: main.py [-h] [--config CONFIG] [-W W] [-H H] [-L L] [--seed SEED] [--cfg CFG] [--steps STEPS] [--fps FPS]
main.py: error: unrecognized arguments: --windows-standalone-build

**Comment by guahunyo** [comment]
![image](https://github.com/chaojie/ComfyUI-AniPortrait/assets/18573180/2a090a9b-b1b7-49cb-837c-2611e559386c)
用了秋叶启动器报错就跟issue1一样

**Comment by guahunyo** [comment]
> ![image](https://private-user-images.githubusercontent.com/18573180/318041607-2a090a9b-b1b7-49cb-837c-2611e559386c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTQwNTYsIm5iZiI6MTcxMTcxMzc1NiwicGF0aCI6Ii8xODU3MzE4MC8zMTgwNDE2MDctMmEwOTBhOWItYjFiNy00OWNiLTgzN2MtMjYxMWU1NTkzODZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDEyMDIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZTNkNWE1NGY2ZjJiOGE1ZThlOGNiOTNjNDhhOThkZTQxZWE1ZjhhODk4NWZlZDQ4MmVjNjE0MjFiZWRkOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.it3NLQ7eNOBh844HmbCcHDwNg0Xp5LFdvxnCrpFWNU4) 用了秋叶启动器报错就跟issue1一样

我git pull 了一下 
![image](https://github.com/chaojie/ComfyUI-AniPortrait/assets/18573180/9bbe0ca3-c43a-4d5b-90c3-a4e6e0f9d40e)
现在报这个错 好像说我缺个config.json

**Comment by guahunyo** [comment]
> > ![image](https://private-user-images.githubusercontent.com/18573180/318041607-2a090a9b-b1b7-49cb-837c-2611e559386c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTQwNTYsIm5iZiI6MTcxMTcxMzc1NiwicGF0aCI6Ii8xODU3MzE4MC8zMTgwNDE2MDctMmEwOTBhOWItYjFiNy00OWNiLTgzN2MtMjYxMWU1NTkzODZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDEyMDIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZTNkNWE1NGY2ZjJiOGE1ZThlOGNiOTNjNDhhOThkZTQxZWE1ZjhhODk4NWZlZDQ4MmVjNjE0MjFiZWRkOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.it3NLQ7eNOBh844HmbCcHDwNg0Xp5LFdvxnCrpFWNU4) 用了秋叶启动器报错就跟issue1一样
> 
> 我git pull 了一下 ![image](https://private-user-images.githubusercontent.com/18573180/318044508-9bbe0ca3-c43a-4d5b-90c3-a4e6e0f9d40e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTYxNjEsIm5iZiI6MTcxMTcxNTg2MSwicGF0aCI6Ii8xODU3MzE4MC8zMTgwNDQ1MDgtOWJiZTBjYTMtYzQzYS00ZDViLTkwYzMtYTRlNmUwZjlkNDBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDEyMzc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NTEwMGFjNGZlMDEzMjhlNDI5YTU4YjZmOGI4ODliYjFlY2Q3OGFlNjdlYTA1MmYxYjIxYmQyYTNkYWU0MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ktl97jhiur7ChFhSceK0EtRzmM5hulrEJmrk2DMtsBk) 现在报这个错 好像说我缺个config.json

应该是我哪个文件路径出问题了 以及老外让我给你带个话
![image](https://github.com/chaojie/ComfyUI-AniPortrait/assets/18573180/94fa2236-75ba-4db7-9994-be7cbe3aff7e)
我也一样  大佬有空的话给个文件夹结构呗

**Comment by guahunyo** [comment]
好的我成功了，问题出在前几天玩了champ ，champ的image_encoder路径没有外面那层，这个多一层sd-image-variations-diffusers
